### ISSUE TITLE
skinner targeting using FinalIK

### ISSUE THREAD

**Issue by Lightsteed** [keijiro/Skinner#12] opened 2017-02-24 12:07 UTC
Hi Keijiro, can you think of any reason why the Skinner mesh would target the particles correctly when animating using the animation controller, but not when using a bone retargeting plugin like Final IK? Basically what happens is the particles will only spawn from a static T pose of the model when using Final IK ( and VR, so VRIK) The root postition does translate, just not the full bone transformaitons and rotations.  I've been working on an application to utilise your effects on a first person model in VR but this has got me stumped. I'm really not very good at programming though so feel free to tell me you cant help :)

thanks!
Josh

**Comment by keijiro** [comment] 2017-02-26 04:20
Actually I have no idea about this issue. Could you provide a minimum project that reproduces the issue?

**Comment by keijiro** [comment] 2017-04-03 02:29
I'm closing this issue. Please feel free to reopen when further information is available.

**Closed as completed by keijiro** 2017-04-03 02:29 UTC
Labels: bug

**Comment by mrlosh** [comment] 2019-05-09 19:15
@Lightsteed did you ever solve this issue? I'm  dealing with the exact same thing.

**Comment by sarahrothberg** [comment] 2019-12-28 04:01
Hello! I am unfortunately having the same problem and really hope there's a solution! I can't post the project, since the problem is with skinner + FinalIK, but I can say for sure that the same exact configuration works if I switch from using VRIK to the Animator. [https://gyazo.com/0b1805499ef13fa39e5ff7e69ec8b208](url) there is a pic of what's going on (the white thing is a second mesh which is properly rigged to my player). Any ideas? Thank you a million for everything you do!!!

**Comment by keijiro** [comment] 2019-12-28 05:06
@sarahrothberg 
I wonder if the script execution order would cause an issue. I'd recommend changing the order between SkinnerSource and FinalIK components, or changing [LateUpdate](https://github.com/keijiro/Skinner/blob/master/Assets/Skinner/SkinnerSource.cs#L183) to Update.

**Comment by sarahrothberg** [comment] 2019-12-28 17:57
changing lateupdate totally worked!!! thanks!
