### ISSUE TITLE
Skinner doesn't work after building when used with SteamVR.

### ISSUE THREAD

**Issue by liamFerris** [keijiro/Skinner#7] opened 2017-01-23 11:28 UTC
We are having problems where a unity build crashes when we use Skinner in conjunction with SteamVR. It works fine when we run in the editor - and Skinner renders well in VR.

`45% memory in use.
8134 MB physical memory [4416 MB free].
9414 MB paging file [4150 MB free].
134217728 MB user address space [134216841 MB free].
Read from location 000043c0 caused an access violation.`

We have also noticed when in editor performance starts out good then after a period of time drops drastically, this happens sooner when you have more Skinner objects, suspected memory leak.

**Comment by keijiro** [comment] 2017-01-23 12:45
I've never tried SteamVR, and actually I have no idea about this issue...

Before diving deep into it, I'd like to check some basic things. Which Unity version are you using?  Could you send the error log of the crashed app?

**Comment by liamFerris** [comment] 2017-01-23 13:01
Hey, thanks for your help - information below

Unity 5.5.0f3 Personal. 

Error Log:

> Initialize engine version: 5.5.0f3 (38b4efef76f0)
> GfxDevice: creating device client; threaded=1
> Direct3D:
>     Version:  Direct3D 11.0 [level 11.0]
>     Renderer: NVIDIA GeForce GTX 970 (ID=0x13c2)
>     Vendor:   NVIDIA
>     VRAM:     3991 MB
>     Driver:   10.18.13.6191
> Begin MonoManager ReloadAssembly
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.dll (this message is harmless)
> Loading C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.dll into Unity Child Domain
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
> Loading C:\Users\Admin\Desktop\projectName\b_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\Assembly-CSharp.dll (this message is harmless)
> Loading C:\Users\Admin\Desktop\projectName\b_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.UI.dll (this message is harmless)
> Loading C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
> Loading C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.PlaymodeTestsRunner.dll (this message is harmless)
> Loading C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.PlaymodeTestsRunner.dll into Unity Child Domain
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.VR.dll (this message is harmless)
> Loading C:\Users\Admin\Desktop\projectName\b_Data\Managed\UnityEngine.VR.dll into Unity Child Domain
> - Completed reload, in  0.152 seconds
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\System.Core.dll (this message is harmless)
> Platform assembly: C:\Users\Admin\Desktop\projectName\b_Data\Managed\System.dll (this message is harmless)
> <RI> Initializing input.
> 
> <RI> Input initialized.
> 
> desktop: 1920x1080 60Hz; virtual: 1920x1080 at 0,0
> <RI> Initialized touch support.
> 
> OpenVR initialized!
>  
> (Filename:  Line: 1754)
> 
> A script behaviour (probably UnityAnimationRecorder?) has a different serialization layout when loading. (Read 32 bytes but expected 120 bytes)
> Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
>  
> (Filename:  Line: 1808)
> 
> UnloadTime: 0.687980 ms
> Connected to lighthouse:LHR-62BFBF24
>  
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 
> Setting up 1 worker threads for Enlighten.
>   Thread -> id: 1bbc -> priority: 1 
> Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
> No Camera tagged as "MainCamera" found.
>  
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 
> UnloadTime: 4.998267 ms
> 
> Unloading 150 unused Assets to reduce memory usage. Loaded Objects now: 14978.
> Total: 4.779506 ms (FindLiveObjects: 0.736145 ms CreateObjectMapping: 0.123674 ms MarkObjects: 1.730826 ms  DeleteObjects: 2.187926 ms)
> 
> Crash!!!
> SymInit: Symbol-SearchPath: '.;C:\Users\Admin\Desktop\projectName;C:\Users\Admin\Desktop\projectName;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Admin'
> OS-Version: 6.3.9600 () 0x100-0x1
> C:\Users\Admin\Desktop\projectName\b.exe:b.exe (00007FF6D1DD0000), size: 23150592 (result: 0), SymType: '-exported-', PDB: 'C:\Users\Admin\Desktop\projectName\b.exe', fileVersion: 5.5.0.46319
> C:\WINDOWS\SYSTEM32\ntdll.dll:ntdll.dll (00007FF962E00000), size: 1753088 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ntdll.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\KERNEL32.DLL:KERNEL32.DLL (00007FF9615B0000), size: 1302528 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\KERNEL32.DLL', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\KERNELBASE.dll:KERNELBASE.dll (00007FF960360000), size: 1134592 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\KERNELBASE.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\HID.DLL:HID.DLL (00007FF95F110000), size: 53248 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\HID.DLL', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\USER32.dll:USER32.dll (00007FF960570000), size: 1536000 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\USER32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\VERSION.dll:VERSION.dll (00007FF95DFB0000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\VERSION.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\ole32.dll:ole32.dll (00007FF960E30000), size: 1654784 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\ole32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\SHLWAPI.dll:SHLWAPI.dll (00007FF961090000), size: 344064 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\SHLWAPI.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\ADVAPI32.dll:ADVAPI32.dll (00007FF960B10000), size: 696320 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\ADVAPI32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\GDI32.dll:GDI32.dll (00007FF961320000), size: 1380352 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\GDI32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\SHELL32.dll:SHELL32.dll (00007FF9616F0000), size: 22122496 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\SHELL32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\OPENGL32.dll:OPENGL32.dll (00007FF9400C0000), size: 1224704 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\OPENGL32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\WINMM.dll:WINMM.dll (00007FF95DF80000), size: 139264 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINMM.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\WS2_32.dll:WS2_32.dll (00007FF960510000), size: 368640 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\WS2_32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\OLEAUT32.dll:OLEAUT32.dll (00007FF961480000), size: 790528 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\OLEAUT32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\IMM32.dll:IMM32.dll (00007FF961550000), size: 221184 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\IMM32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\DNSAPI.dll:DNSAPI.dll (00007FF95F5C0000), size: 671744 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DNSAPI.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL:IPHLPAPI.DLL (00007FF959D90000), size: 172032 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\WINHTTP.dll:WINHTTP.dll (00007FF9572E0000), size: 823296 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINHTTP.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\msvcrt.dll:msvcrt.dll (00007FF960D80000), size: 696320 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\msvcrt.dll', fileVersion: 7.0.9600.17415
> C:\WINDOWS\SYSTEM32\combase.dll:combase.dll (00007FF9610F0000), size: 2166784 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\combase.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\RPCRT4.dll:RPCRT4.dll (00007FF9609C0000), size: 1314816 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\RPCRT4.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\sechost.dll:sechost.dll (00007FF960BC0000), size: 364544 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\sechost.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\GLU32.dll:GLU32.dll (00007FF94D730000), size: 188416 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\GLU32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\DDRAW.dll:DDRAW.dll (00007FF94A2E0000), size: 1015808 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DDRAW.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\WINMMBASE.dll:WINMMBASE.dll (00007FF95DE00000), size: 172032 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINMMBASE.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\NSI.dll:NSI.dll (00007FF9615A0000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\NSI.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\MSCTF.dll:MSCTF.dll (00007FF960C20000), size: 1388544 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\MSCTF.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\WINNSI.DLL:WINNSI.DLL (00007FF959D70000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINNSI.DLL', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\DCIMAN32.dll:DCIMAN32.dll (00007FF95A510000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DCIMAN32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\cfgmgr32.dll:cfgmgr32.dll (00007FF960310000), size: 323584 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\cfgmgr32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\DEVOBJ.dll:DEVOBJ.dll (00007FF95ED40000), size: 163840 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DEVOBJ.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\kernel.appcore.dll:kernel.appcore.dll (00007FF95ED90000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\kernel.appcore.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\CRYPTBASE.dll:CRYPTBASE.dll (00007FF95FE40000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\CRYPTBASE.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll:bcryptPrimitives.dll (00007FF95FDD0000), size: 405504 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\uxtheme.dll:uxtheme.dll (00007FF95EBC0000), size: 1216512 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\uxtheme.dll', fileVersion: 6.3.9600.17415
> C:\Users\Admin\Desktop\projectName\b_Data\Mono\mono.dll:mono.dll (00007FF944790000), size: 2998272 (result: 0), SymType: '-exported-', PDB: 'C:\Users\Admin\Desktop\projectName\b_Data\Mono\mono.dll', fileVersion: 1.0.0.1
> C:\WINDOWS\system32\PSAPI.DLL:PSAPI.DLL (00007FF961310000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\PSAPI.DLL', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\MSWSOCK.dll:MSWSOCK.dll (00007FF95F7C0000), size: 364544 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSWSOCK.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\shcore.dll:shcore.dll (00007FF95EAA0000), size: 729088 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\shcore.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\dwmapi.dll:dwmapi.dll (00007FF95E5F0000), size: 135168 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\dwmapi.dll', fileVersion: 6.3.9600.17415
> C:\Program Files\WIDCOMM\Bluetooth Software\btmmhook.dll:btmmhook.dll (00007FF94F5A0000), size: 262144 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files\WIDCOMM\Bluetooth Software\btmmhook.dll', fileVersion: 12.0.1.940
> C:\WINDOWS\SYSTEM32\d3d11.dll:d3d11.dll (00007FF95CCB0000), size: 2306048 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\d3d11.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\dxgi.dll:dxgi.dll (00007FF95DAD0000), size: 552960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dxgi.dll', fileVersion: 6.3.9600.17415
> C:\Users\Admin\Desktop\projectName\b_Data\Plugins\openvr_api.dll:openvr_api.dll (00007FF94E8B0000), size: 323584 (result: 0), SymType: '-exported-', PDB: 'C:\Users\Admin\Desktop\projectName\b_Data\Plugins\openvr_api.dll'
> C:\WINDOWS\SYSTEM32\profapi.dll:profapi.dll (00007FF95FF50000), size: 86016 (result: 0), SymType: '-nosymbols-', PDB: 'C:\WINDOWS\SYSTEM32\profapi.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\SETUPAPI.dll:SETUPAPI.dll (00007FF962C10000), size: 1941504 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\SETUPAPI.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\WINTRUST.dll:WINTRUST.dll (00007FF9600D0000), size: 331776 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\WINTRUST.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\CRYPT32.dll:CRYPT32.dll (00007FF960130000), size: 1961984 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\CRYPT32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\MSASN1.dll:MSASN1.dll (00007FF960000000), size: 69632 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\MSASN1.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\nvapi64.dll:nvapi64.dll (00007FF95D290000), size: 3854336 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\nvapi64.dll', fileVersion: 10.18.13.6191
> C:\WINDOWS\SYSTEM32\nvwgf2umx.dll:nvwgf2umx.dll (00007FF95B440000), size: 18718720 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\nvwgf2umx.dll', fileVersion: 10.18.13.6191
> C:\WINDOWS\SYSTEM32\bcrypt.dll:bcrypt.dll (00007FF95FA70000), size: 155648 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\bcrypt.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\clbcatq.dll:clbcatq.dll (00007FF960FD0000), size: 745472 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\clbcatq.dll', fileVersion: 2001.12.10530.17415
> C:\WINDOWS\system32\wbem\wbemprox.dll:wbemprox.dll (00007FF951430000), size: 69632 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\wbemprox.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\wbemcomn.dll:wbemcomn.dll (00007FF953430000), size: 532480 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\wbemcomn.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\CRYPTSP.dll:CRYPTSP.dll (00007FF95F820000), size: 131072 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\CRYPTSP.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\rsaenh.dll:rsaenh.dll (00007FF95F440000), size: 221184 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\rsaenh.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\wbem\wbemsvc.dll:wbemsvc.dll (00007FF951130000), size: 86016 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\wbemsvc.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\system32\wbem\fastprox.dll:fastprox.dll (00007FF951150000), size: 1028096 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\fastprox.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\System32\MMDevApi.dll:MMDevApi.dll (00007FF95DA00000), size: 458752 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\MMDevApi.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\wdmaud.drv:wdmaud.drv (00007FF95ABE0000), size: 253952 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\wdmaud.drv', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\ksuser.dll:ksuser.dll (00007FF959DC0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ksuser.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\AVRT.dll:AVRT.dll (00007FF95CEF0000), size: 49152 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\AVRT.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (00007FF949B60000), size: 516096 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\AUDIOSES.DLL', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\powrprof.dll:powrprof.dll (00007FF95FE50000), size: 286720 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\powrprof.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\msacm32.drv:msacm32.drv (00007FF95ABD0000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\msacm32.drv', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\MSACM32.dll:MSACM32.dll (00007FF95ABB0000), size: 114688 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSACM32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\midimap.dll:midimap.dll (00007FF949BE0000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\midimap.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\xinput1_3.dll:xinput1_3.dll (000000000A200000), size: 122880 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\xinput1_3.dll', fileVersion: 9.18.944.0
> C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\vrclient_x64.dll:vrclient_x64.dll (00007FF93CDB0000), size: 2953216 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\vrclient_x64.dll'
> C:\WINDOWS\SYSTEM32\MSVCP120.dll:MSVCP120.dll (00007FF9580D0000), size: 679936 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSVCP120.dll', fileVersion: 12.0.21005.1
> C:\WINDOWS\SYSTEM32\MSVCR120.dll:MSVCR120.dll (00007FF957FE0000), size: 978944 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSVCR120.dll', fileVersion: 12.0.21005.1
> C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\driver_lighthouse.dll:driver_lighthouse.dll (00007FF94D050000), size: 1744896 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\driver_lighthouse.dll'
> C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\aitcamlib.dll:aitcamlib.dll (00007FF95CF70000), size: 57344 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\aitcamlib.dll'
> C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\AitUVCExtApi.dll:AitUVCExtApi.dll (00007FF95CAD0000), size: 114688 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\AitUVCExtApi.dll', fileVersion: 1.0.0.2
> C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\AitH264Capture.dll:AitH264Capture.dll (00007FF94BD50000), size: 2662400 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\AitH264Capture.dll', fileVersion: 1.0.0.2
> C:\WINDOWS\SYSTEM32\MSIMG32.dll:MSIMG32.dll (00007FF95DEE0000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSIMG32.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\WINSPOOL.DRV:WINSPOOL.DRV (00007FF95D710000), size: 532480 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINSPOOL.DRV', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\OLEACC.dll:OLEACC.dll (00007FF95D6A0000), size: 434176 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\OLEACC.dll', fileVersion: 7.2.9600.17415
> C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.9600.17415_none_932b3b5547500489\gdiplus.dll:gdiplus.dll (00007FF95D850000), size: 1769472 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.9600.17415_none_932b3b5547500489\gdiplus.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL:dhcpcsvc6.DLL (00007FF959840000), size: 90112 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL:dhcpcsvc.DLL (00007FF959A40000), size: 106496 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL', fileVersion: 6.3.9600.17415
> C:\Windows\System32\rasadhlp.dll:rasadhlp.dll (00007FF9523C0000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\System32\rasadhlp.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\System32\fwpuclnt.dll:fwpuclnt.dll (00007FF9599D0000), size: 438272 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\fwpuclnt.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\dbghelp.dll:dbghelp.dll (00007FF94E9E0000), size: 1613824 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dbghelp.dll', fileVersion: 6.3.9600.17415
> C:\WINDOWS\SYSTEM32\SspiCli.dll:SspiCli.dll (00007FF95FD80000), size: 188416 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\SspiCli.dll', fileVersion: 6.3.9600.17415
> 
> ========== OUTPUTING STACK TRACE ==================
> 
> 0x00007FF6D268EB50 (b) physx::shdfnd::ErrorHandler::getMaxCallbackNum
> 0x00007FF6D1F5BA88 (b) physx::shdfnd::Foundation::getNamedAllocMap
> 0x00007FF6D1F5BB7A (b) physx::shdfnd::Foundation::getNamedAllocMap
> 0x00007FF6D1F9A99F (b) physx::shdfnd::Foundation::getNamedAllocMap
> 0x00007FF6D1F99D59 (b) physx::shdfnd::Foundation::getNamedAllocMap
> 0x00007FF6D1F9AD9F (b) physx::shdfnd::Foundation::getNamedAllocMap
> 0x00007FF6D1F99436 (b) physx::shdfnd::Foundation::getNamedAllocMap
> 0x00007FF6D20A78F7 (b) physx::shdfnd::Foundation::getNamedAllocMap
> 0x00007FF6D25FC013 (b) physx::shdfnd::ErrorHandler::getMaxCallbackNum
> 0x00007FF6D26019FF (b) physx::shdfnd::ErrorHandler::getMaxCallbackNum
> 0x00007FF6D25FA11A (b) physx::shdfnd::Allocator::`default constructor closure'
> 0x00007FF6D20580C8 (b) physx::shdfnd::Foundation::getNamedAllocMap
> 0x00007FF9615B13D2 (KERNEL32) BaseThreadInitThunk
> 0x00007FF962E703C4 (ntdll) RtlUserThreadStart
> 
> ========== END OF STACKTRACE ===========
> 
> **** Crash! ****

**Comment by keijiro** [comment] 2017-01-23 14:45
Thanks for the information! I was a bit surprised because that crash point is totally unexpected for me... it looks like an unknown issue of Unity.

Could you provide a minimum project that reproduces this issue? I'd like to look into it and make a report if it's a new issue.

**Comment by liamFerris** [comment] 2017-01-23 18:40
Hey,
[This project](https://github.com/liamFerris/SkinnerTest) reproduces the issue, as you can tell from the crash folder included. 
All it includes is SteamVR and this repo. 
It works fine when ran within unity (and looks great in vr), but when you build the project and then run from the .exe it crashes.

**Comment by keijiro** [comment] 2017-01-24 04:24
Thank you very much for providing the project. I'll look into it later.

**Comment by keijiro** [comment] 2017-01-24 11:02
The issue reproduced with your project, but I found some issues in the project.

- Is the sphere model in your project actually skinned? I'm not sure how you made this Skinner model, but it looks not skinned.
- A MeshFilter component in LeafyBreezeSkinnerBody is not needed. I guess that this is the root cause of the crash.
- Attaching multiple Skinner effect components to a single game object may cause a problem. Please remove one of the effects in LeafyBreezeSkinnerController.

I succeeded to run the project without a crash after fixing these issues.

**Comment by keijiro** [comment] 2017-01-26 11:55
I'm closing this issue. Please feel free to reopen if you find further issues.

**Closed as completed by keijiro** 2017-01-26 11:55 UTC
Labels: question
